development: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/photopin_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', "postgres://localhost:5432/photopin_test#{ENV['TEST_ENV_NUMBER']}") %>

production:
  <<: *default
